#! /bin/sh

sxhkd &

bspc monitor -d 一 二 三 四 五 六 七 八 九 十
#bspc monitor -d 6 7 8 IV V VI VII VIII IX X

bspc config initial_polarity first_child
bspc config border_width         1
bspc config window_gap           0
bspc config top_padding	-5

bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_follows_pointer   true

#bspc rule -a Spotify desktop='^10'
bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

polybar bar &
