#!/usr/bin/env zsh
set -e

CWD="$(readlink -f $0 | xargs dirname)"

setup() {
	source "$CWD/$1/setup"
}

error() {
	echo "Error: $1"
	echo "exiting"
	exit 1
}

command -v "git" > /dev/null || error "Missing git"
command -v "wget" > /dev/null || error "Missing wget"
command -v "curl" > /dev/null || error "Missing curl"
command -v "jq" > /dev/null || error "Missing jq"

[[ "$#" == 0 ]] && error "No target provided"

install -d "$HOME/.local/bin"
install -d "$HOME/.local/lib"

#git clone git@github.com:johnche/brrr "$HOME/.local/brrr"
#$HOME/.local/brrr/brrr

for target in "$@"; do
	echo "Installing $target"
	setup "$target"
done
