#!/usr/bin/env zsh

declare -r CWD="$(readlink -f $0 | xargs dirname)"

curl -fLo "$HOME/.config/nvim/autoload/plug.vim" --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

ln -s "$CWD/init.vim" "$HOME/.config/nvim/init.vim"
ln -s "$CWD/modules" "$HOME/.config/nvim/modules"
ln -s "$CWD/after" "$HOME/.config/nvim/after"
