fpath=("$HOME/.config/zsh/pure" $fpath)

export XDG_CONFIG_HOME="$HOME/.config"
export DOOMDIR="$XDG_CONFIG_HOME/doom"

export GOPATH="$HOME/.local/go"
export GOBIN="$GOPATH/bin"

export PYENV_ROOT="$XDG_CONFIG_HOME/pyenv"

# SDKMAN / jdk
export SDKMAN_DIR="$HOME/.local/lib/sdkman"
export SDKMAN_DIR_RAW='$HOME/.local/lib/sdkman'

export EDITOR='vim'
export GIT="$HOME/git"
export GREP_OPTIONS='--color=auto'

# Requires source-highlight package
#export LESSOPEN='| /opt/local/bin/src-hilite-lesspipe.sh %s'
export LESS=' -R '

#. "$HOME/.cargo/env"
