fpath=("$HOME/.config/zsh/pure" $fpath)

export XDG_CONFIG_HOME="$HOME/.config"
export DOOMDIR="$XDG_CONFIG_HOME/doom"

export PREFIX=$HOME/.local

# macos dynamic lib patching
export DYLD_FALLBACK_LIBRARY_PATH="$PREFIX/lib"

export NPM_CONFIG_PREFIX="$PREFIX/state/npm"

export GOPATH="$PREFIX/go"
export GOBIN="$GOPATH/bin"

export PYENV_ROOT="$XDG_CONFIG_HOME/pyenv"

# SDKMAN / jdk
export SDKMAN_DIR="$PREFIX/share/sdkman"
export SDKMAN_DIR_RAW='$PREFIX/share/sdkman'

#. "$HOME/.cargo/env"
