fpath=("$HOME/.config/zsh/pure" $fpath)

export XDG_CONFIG_HOME="$HOME/.config"
export DOOMDIR="$XDG_CONFIG_HOME/doom"

export PREFIX=$HOME/.local

# macos dynamic lib patching
export DYLD_FALLBACK_LIBRARY_PATH="$PREFIX/lib"

# macports headers
export CPATH="/opt/local/include"
export LIBRARY_PATH="/opt/local/lib"

export NPM_CONFIG_PREFIX="$PREFIX/state/npm"

export GOPATH="$PREFIX/go"
export GOBIN="$GOPATH/bin"

export LOCAL_BIN="$HOME/.local/bin"

export PYENV_ROOT="$XDG_CONFIG_HOME/pyenv"

# SDKMAN / jdk
export SDKMAN_DIR="$PREFIX/share/sdkman"
export SDKMAN_DIR_RAW='$PREFIX/share/sdkman'

# Making ssh agent run as a service on macos is alot of work
if [ "$SSH_AUTH_SOCK" = "" -a -x /usr/bin/ssh-agent ]; then
	eval `/usr/bin/ssh-agent`
fi

. "$HOME/.cargo/env"
