source "$HOME/.config/zsh/zsh_options"
source "$HOME/.config/zsh/pathvars"
source "$HOME/.config/zsh/aliases"

export NPM_CONFIG_PREFIX=$HOME/.local
export PREFIX=$HOME/.local/bin
export FZF_DEFAULT_COMMAND='rg --files --follow --no-ignore-vcs --hidden -g "!{node_modules/*,.git/*}"'

eval "$(direnv hook zsh)"

# =========== Keep at end ===============
# Ad hoc configs
find "$XDG_CONFIG_HOME/zsh/plugged" -type f | while read file; do source "$file"; done

source "$XDG_CONFIG_HOME/zsh/syntax-highlighting/zsh-syntax-highlighting.zsh"

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
[[ -s "$HOME/.local/lib/sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.local/lib/sdkman/bin/sdkman-init.sh"
